configme: remove decheckpoint call
By the time configme is run, the tree is long since
de-checkpointed. Doing this again clobbers local changes,
so we'll just comment the call out (in case it is required
in the future).

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/configme b/tools/configme
--- a/tools/configme
+++ b/tools/configme
@@ -239,11 +239,11 @@ done
 
 echo "[INFO] Finding user(s) of current branch: $CURRENT"
 
-decheckpoint
-if [ $? != 0 ]; then
-	echo Restoring wrs data from wrs_meta branch failed
-	exit 1
-fi
+# decheckpoint
+# if [ $? != 0 ]; then
+#	echo Restoring wrs data from wrs_meta branch failed
+#	exit 1
+# fi
 
 # Note the space and EOL anchor.  We want to find the SCC file where
 # CURRENT is on the far RHS, i.e. the one that created the branch,
