configme: catch errors found during fragment sanitization
During the pre merge processing of fragments and error is thrown
if a fragment doesn't exist. configme wasn't checking the return
code from the sanity script, and hence would continue processing
and produce a .config that would be missing options for any fragment
that followed the one in error.

Catching the error, and propagating it up to the calling build
system exposes this to the user .. who can then fix the problem.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/configme b/tools/configme
--- a/tools/configme
+++ b/tools/configme
@@ -135,6 +135,11 @@ run_board_config()
 
     frags=`cat $META_DIR/cfg/$KTGT/config_frag.txt | sed 's%\(^.*$\)%'$META_DIR/cfg'\1%'`
     pre_config -l $META_DIR/cfg/$KTGT/ $frags > $META_DIR/cfg/$KTGT/config.log 2>&1
+    if [ $? -ne 0 ]; then
+	echo "ERROR: could not sanitize configuration fragments"
+	echo "   errors are logged in $META_DIR/cfg/$KTGT/config.log"
+	exit 1
+    fi
 
     # remove any old assembled debug fragments
     rm -f $BUILD_DIR/.tmp.config*
