kgit-meta: do not restore starting branch
After executing kgit-meta the checked out branch is the one that
the feature descriptions dictate. This should be the branch we
continue processing, so checking out the original branch is
counter productive.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kgit-meta b/tools/kgit-meta
--- a/tools/kgit-meta
+++ b/tools/kgit-meta
@@ -1234,16 +1234,19 @@ if [ -n "$_patch_apply" ]; then
 	exit 1
     fi
 
-    git checkout -q $orig_branch
-    r=$?
-    if [ $r -ne 0 ]; then
-	git checkout -q $orig_branch/base
-	r=$?
-	if [ $r -ne 0 ]; then
-	    echo [ERROR] git checkout of \"$orig_branch\" failed
-	    exit $r
-	fi
-    fi
+    # no longer required. This should be ensured by the caller, 
+    # not the script. But kept around as a temporary reference, since
+    # it may be come optional functionality going forward.
+    # git checkout -q $orig_branch
+    # r=$?
+    # if [ $r -ne 0 ]; then
+    # 	git checkout -q $orig_branch/base
+    # 	r=$?
+    # 	if [ $r -ne 0 ]; then
+    # 	    echo [ERROR] git checkout of \"$orig_branch\" failed
+    # 	    exit $r
+    # 	fi
+    # fi
 fi
 
 #
