scc/kgit-meta: report missing config fragments by name
If a configuration fragment was missing, the previous error output
was not clear about the error:

| [INFO] doing kernel configme
| [INFO] Configuring target/machine combo: "standard/atom-pc"
| [INFO] collecting configs in ./meta/meta-series
| ERROR: could not sanitize configuration fragments
|    errors are logged in ... linux/meta/cfg/standard/atom-pc/config.log

but we know the name of the missing fragment and can improve the error
message to be this:

| [ERROR] kernel configuration fragment fragment 'virto.cfg' cannot be found
| ERROR. A meta series could not be created for branch yocto/standard/common-pc/atom-pc
| ERROR. Could not locate meta series for atom-pc
| ERROR. Could not apply patches for atom-pc.
|        Patch failures can be resolved in the devshell (bitbake -c devshell linux-yocto)

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kgit-meta b/tools/kgit-meta
--- a/tools/kgit-meta
+++ b/tools/kgit-meta
@@ -1225,6 +1225,11 @@ if [ -n "$_kconf" ]; then
 		fragname=`echo $entry | awk '{print $4}'`
 		reloc_frag=`_strip_common_prefix $fragname`
 
+		if [ ! -f "$fragname" ]; then
+			echo "[ERROR] frag $fragname does not exist"
+			exit 1
+		fi
+
 		if [ x$fragtype = xhardware ]; then
 			echo "$reloc_frag" >> $meta_dir/cfg/$KTGT/hdw_frags.txt
 			echo "$reloc_frag" >> $meta_dir/cfg/$KTGT/$fraglist
diff --git a/tools/scc b/tools/scc
--- a/tools/scc
+++ b/tools/scc
@@ -482,6 +482,11 @@ kconf()
 	this_frag=`search_include_paths $2`
     fi
 
+    if [ ! -f "$this_frag" ]; then
+	echo "[ERROR] kernel configuration fragment fragment '$2' cannot be found"
+	exit 1
+    fi
+
     if [ "$last_cmd" == "patch" ]; then
         _dump " \\"
 	_dump -n "  echo \"# _kconf $type $this_frag\";"
