kgit-publish: use mktemp for intermediary tree
We currently don't clean up from a failed tree "publish", and
so the dir of $src.tmp is not unique, and may exist with some
content.  If it exists, the attempt to re-use it can fail, as
shown below:

  treegen$KMETA=meta-ovp kgit-publish -c -a tree tree-pub
  Switched to branch 'meta-ovp'
  [meta-ovp b0e9067] meta: add README
   1 file changed, 1 insertion(+)
  [ERROR]: git commit 00-README failed
  [ERROR] checkpoint failed

The fail is because $src.tmp already exists and has some/all of
the intended commits.  Rather than nuke-and-pave over the old
dir, simply create a unique one, since the old data may be key
in debugging random issues.

Also add error checking on the copy command.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>

diff --git a/tools/kgit-publish b/tools/kgit-publish
--- a/tools/kgit-publish
+++ b/tools/kgit-publish
@@ -112,15 +112,23 @@ if [ ! -d "$dest" ] || [ -n "$force" ]; then
 	rm -rf "$dest"
     fi
 
-    if [ ! -d "$src.tmp" ]; then
-	if [ -n "$verbose" ]; then
-	    echo "[INFO] making working copy of $src as $src.tmp"
-	fi
-	cp -r $src $src.tmp
+    SRCTMP=`mktemp -d --tmpdir=./`
+    if [ $? != 0 ]; then
+	echo "[ERROR] mktemp failed"
+	exit -1
     fi
 
-    # now we only operate on src.tmmp
-    src=$src.tmp
+    if [ -n "$verbose" ]; then
+	    echo "[INFO] making working copy of $src in $SRCTMP"
+    fi
+    cp -a $src $SRCTMP
+    if [ $? != 0 ]; then
+	echo "[ERROR] making working copy of $src failed"
+	exit -1
+    fi
+
+    # now we only operate on temp copy
+    src=$SRCTMP/$src
 
     x=`cd $src; git show-ref checkpoint_start`
     if [ -z "$x" ]; then
