kgit-scc: allow for original branch name to change
Sometimes the processing of a meta series changes the
original branch name, which causes and error when we try
and restore it. Simply checking for the renamed branch
before erroring fixes the problem.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kgit-meta b/tools/kgit-meta
--- a/tools/kgit-meta
+++ b/tools/kgit-meta
@@ -1207,8 +1207,12 @@ if [ -n "$_patch_apply" ]; then
     git checkout -q $orig_branch
     r=$?
     if [ $r -ne 0 ]; then
-	echo [ERROR] git checkout of \"$orig_branch\" failed
-	exit $r
+	git checkout -q $orig_branch/base
+	r=$?
+	if [ $r -ne 0 ]; then
+	    echo [ERROR] git checkout of \"$orig_branch\" failed
+	    exit $r
+	fi
     fi
 fi
 
