kgit-init: make content creation optional
It isn't always desireable that kgit-init create branches and
commits, in particular when a custom repository is being used
that may or may not contain existing branches. If content is
not supposed to be created, the repository is conditioned and
staged, but no branches or commits are created.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kgit-init b/tools/kgit-init
--- a/tools/kgit-init
+++ b/tools/kgit-init
@@ -24,6 +24,9 @@ export LC_ALL
 path=`dirname $0`
 . $path/kgit
 
+# copy a defined set of tools/scripts/resources into the tree that
+# we are constructing. We want to make everything available that was
+# used to build the tree.
 install_resources()
 {
     # look in our directory for:
@@ -31,36 +34,20 @@ install_resources()
     #   guilt-*
     #   generate_cfg, kconf_check, configme
 
-    ls $path/kgit-* &> /dev/null
-    if [ $? -eq 0 ]; then
-	tools=`echo "$tools"; ls $path/kgit-*; ls $path/kgit`
-    fi
-    ls $path/guilt-* &> /dev/null
-    if [ $? -eq 0 ]; then
-	tools=`echo "$tools"; ls $path/guilt-*`
-    fi
-    if [ -e $path/scc ]; then
-	tools=`echo "$tools"; echo "$path/scc"`
-    fi
-    if [ -e $path/generate_cfg ]; then
-	tools=`echo "$tools"; echo "$path/generate_cfg"`
-    fi
-    if [ -e $path/kconf_check ]; then
-	tools=`echo "$tools";  echo "$path/kconf_check"`
-    fi
-    if [ -e $path/kconf_check ]; then
-	tools=`echo "$tools";  echo "$path/configme"`
-    fi
-    
-    if [ -n "$tools" ]; then
-	mkdir -p $meta_dir/scripts
-	for s in $tools; do
- 	    cp $s $meta_dir/scripts
-	done
-    fi
+    tools_list="kgit kgit-* guilt-* scc generate_cfg kconf_check configme patchme updateme creatme"
+
+    mkdir -p $meta_dir/scripts/
+    for pattern in $tools_list; do
+	ls $path/$pattern &> /dev/null
+	if [ $? -eq 0 ]; then
+	    cp $path/$pattern $meta_dir/scripts
+	fi
+    done
 }
 
-# make sure you are in the target repo when calling this
+# make sure you are in the target repo when calling this, it removes all
+# branches that were created as part of an old tree consruction cna
+# provides a clean slate.
 clean_tgt_repo()
 {
     if [ -n "$verbose" ]; then
@@ -69,8 +56,9 @@ clean_tgt_repo()
 
     if [ -d .git ]; then
 	# Keep tags that came from kernel.org; delete the rest, i.e.
-	# v2.6.nn and v2.6.nn-rcM and v2.6.nn.M (nn=10,11, ..99, M=0,1, ...99)
-	for tg in `git tag| grep -v 'v2.6.[0-9]\{2\}\(\(-rc[0-9]\{1,2\}\)\{0,1\}$\|\.[0-9]\{1,2\}$\)'`
+	# v3.nn, v2.6.nn and v2.6.nn-rcM and v2.6.nn.M (nn=10,11, ..99, M=0,1, ...99)
+	for tg in `git tag| grep -v 'v2.6.[0-9]\{2\}\(\(-rc[0-9]\{1,2\}\)\{0,1\}$\|\.[0-9]\{1,2\}$\)' |
+                            grep -v 'v3.[0-9]\{2\}\(\(-rc[0-9]\{1,2\}\)\{0,1\}$\|\.[0-9]\{1,2\}$\)'`
 	do
 	    git tag -d $tg > /dev/null
 	done
@@ -158,7 +146,8 @@ if [ ! $# -gt 0 ]; then
     exit
 fi
 
-# blindly guess that everything was passed
+# assign the default set of arguments
+#   source tree, branch point and destination
 src=$1
 initial_branch_point=$2
 dest=$3
@@ -194,7 +183,7 @@ if [ -z "$src" ] && [ ! -d "$src" ]; then
 fi
 
 if [ -z "$message" ]; then
-    message="WR Linux baseline"
+    message="base: add .gitignore and exclusions"
 fi
 
 # figure out what type of type destination repository we are creating
@@ -264,27 +253,32 @@ if [ -n "$new_repo" ]; then
 	    if [ -n "$clean" ]; then
 		clean_tgt_repo
 	    fi
-		
-	    # check to see if there is already a content branch
-	    git show-ref --quiet --verify -- "refs/heads/$content_branch";
-	    if [ $? -eq 1 ]; then
-	    	if [ -n "$verbose" ]; then
-	    	    echo "[INFO] creating branch $content_branch from $initial_branch_point";
-	    	else
-	    	    checkout_opts=-q
-	    	fi
-	    	git checkout -f $checkout_opts -b $content_branch $initial_branch_point
-	    	r=$?
-	    	if [ $r -ne 0 ]; then
-	    	    echo [ERROR] git checkout of \"$initial_branch_point\" failed
-	    	    exit $r
-	    	fi
+
+	    if [ -n "$init_creates_content" ]; then
+	        # check to see if there is already a content branch
+		git show-ref --quiet --verify -- "refs/heads/$content_branch";
+		if [ $? -eq 1 ]; then
+	     	    if [ -n "$verbose" ]; then
+	     		echo "[INFO] creating branch $content_branch from $initial_branch_point";
+	     	    else
+	     		checkout_opts=-q
+	     	    fi
+	     	    git checkout -f $checkout_opts -b $content_branch $initial_branch_point
+	     	    r=$?
+	     	    if [ $r -ne 0 ]; then
+	     		echo [ERROR] git checkout of \"$initial_branch_point\" failed
+	     		exit $r
+	     	    fi
+		else
+	     	    # change the type of repo ...
+	     	    git checkout -f $content_branch
+	     	    existing_repo=t
+	     	    new_repo=
+	     	    existing_repo_no_metadata=
+		fi
 	    else
-	    	# change the type of repo ...
-	    	git checkout -f $content_branch
-	    	existing_repo=t
-	    	new_repo=
-	    	existing_repo_no_metadata=
+		git checkout -f $checkout_opts master
+		git reset --hard $initial_branch_point
 	    fi
 	else
 	    git clone $clone_opt $src $dest
@@ -341,25 +335,29 @@ if [ -n "$new_repo" ] || [ -n "$existing_but_flat_repo" ]; then
 	cat .gitignore | sed s%^patches%#patches% | \
             sed s%^series%#series% > .gitignore.tmp
 	mv .gitignore.tmp .gitignore
-	echo "/LDAT_LINUX_PATCHES" >> .gitignore
 	echo "/$meta_dir" >> .gitignore
-	git add .gitignore 
-        git commit -m "gitignore: adding base exclusions"
+
+	if [ -n "$init_creates_content" ]; then
+	    git add .gitignore 
+            git commit -m "gitignore: adding base exclusions"
+	fi
     else
 	touch .gitignore
     fi
 
-    echo "Initial creation marker" > .create_stamp
-    git add -f .create_stamp
-    git add -f .gitignore
+    if [ -n "$init_creates_content" ]; then
+	echo "Initial creation marker" > .create_stamp
+	git add -f .create_stamp
+	git add -f .gitignore
 
-    git commit -q -m "$message"
+	git commit -q -m "$message"
+    fi
 
     # create a meta-information branch
     git branch $meta_branch $initial_branch_point
 
     # tag the base
-    git tag "meta_`date +%F`"
+    git tag "meta_`date +%F`" $initial_branch_point
 fi
 
 if [ -n "$existing_repo" ]; then
