kgit-meta: add error checking and autoconfiguration to git commands
Fixes [YOCTO #1838]

When git commands are embedded into feature descriptions, they can
fail for a variety of reasons. The current meta series processing does
not trap errors, and will continue to process potentially failing
commands. All git commands are now checked for their return code, and
in case of error, the error code is passed up via early exit.

A second common git issue is on a new machine that has not been
configured with a username/email for commits. This is now detected
by checking for a global user.name. If one is not found, a local
user name of "Auto Configured" and email of "auto.configured" is
created to allow git operations to succeed.

Signed-off-by: Bruce Ashfield <bruce@windriver.com>

diff --git a/tools/kgit-meta b/tools/kgit-meta
--- a/tools/kgit-meta
+++ b/tools/kgit-meta
@@ -807,6 +807,11 @@ do_git()
 		 fi
 
 		 eval git $cmd
+		 ret=$?
+		 if [ $ret -ne 0 ]; then
+		     echo "ERROR: could not complete git cmd \"git $cmd\""
+		     exit $ret
+		 fi
 		 ;;
 	esac
     fi
@@ -977,6 +982,18 @@ wrap_meta_series()
     fi
 }
 
+# Checks that git is configured properly for merge/commit operations
+# If it isn't globally configured, the repository is configured locally
+# to allow commits to the repo
+git_sanity_check()
+{
+    git config --global --get user.name > /dev/null
+    if [ $? -ne 0 ]; then
+	git config user.name "Auto Configured"
+	git config user.email "auto.configured"
+    fi
+}
+
 #
 # gather and organize the information require to generate a repo
 if [ -n "$_rc_file" ] && [ -e "$_rc_file" ]; then
@@ -1047,6 +1064,8 @@ if [ -n "$_patch_apply" ]; then
     if [ -n "$verbose" ]; then
 	echo "[INFO] validating against known patches  (`basename $_meta_series`)"
     fi
+
+    git_sanity_check
 
     # this will actually apply the patches and tag the tree
     # process_meta_series "patch"
