kgit-s2q: warn/exit with error if patch not in series
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>

diff --git a/tools/kgit-s2q b/tools/kgit-s2q
--- a/tools/kgit-s2q
+++ b/tools/kgit-s2q
@@ -440,3 +440,12 @@ do
 		fi
 	fi
 done
+
+# if we've failed to locate $START in the series, and
+# not subsequently cleared $START, then something evil
+# has happened, and we'll do nothing and silently
+# return zero which otherwise would be nasty.
+if [ -n "$START" ]; then
+	echo Failed to locate $START in the series
+	exit 1
+fi
