kern-tools: use .meta as meta data container
Previously the meta directory was added to all .gitignore files, otherwise
all users of the kernel would see an untracked directory "meta". This
caused workflow issues, since the same .gitignore was shared on the meta
branch itself. Which meant that changes were not shown and files needed to
be added with the -f flag.

To fix this, we teach the tools to look for .$META as the meta data
container, and place the meta branches directory under that same name.

The result is that the .meta directory is ignored by git automatically, but
is available to all branches. And switching to the meta branch no longer
warns of clobbered files, and once you arrive, files are tracked and
manipulated normally.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kgit-meta b/tools/kgit-meta
--- a/tools/kgit-meta
+++ b/tools/kgit-meta
@@ -752,9 +752,7 @@ do_patch()
 
 	    if [ -d $patches_dir ] && [ ! -d $patches_dir/links ]; then
     		$(  cd $patches_dir; 
-                    if [ -f links ]; then
-			rm -f links
-		    fi 
+		    rm -f links
 		    ln -s $relative_dir/$meta_dir/cfg links
 		)
 	    fi
@@ -1000,8 +998,11 @@ fi
 
 meta_dir=`find_dir $meta_dir_name`
 if [ -z "$meta_dir" ]; then
-    echo "ERROR cannot locate '$meta_dir_name' directory"
-    exit 1
+    meta_dir=`find_dir ".$meta_dir_name"`
+    if [ -z "$meta_dir" ]; then
+	echo "ERROR cannot locate '$meta_dir_name' directory"
+	exit 1
+    fi
 fi
 
 work_cfg_dir=$meta_dir/cfg
