kgit-init: check for valid branchpoint
When generating a tree, it is (unfortunately) common that the
base tree doesn't contain the tag that the user thinks it does.
In this case, we should abort the tree generation and report a
clear error.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kgit-init b/tools/kgit-init
--- a/tools/kgit-init
+++ b/tools/kgit-init
@@ -279,7 +279,11 @@ if [ -n "$new_repo" ]; then
 		fi
 	    else
 		git checkout -q -f $checkout_opts master
-		git reset --hard $initial_branch_point
+		git reset --hard $initial_branch_point &> /dev/null
+		if [ $? -ne 0 ]; then
+		    echo "[ERROR] branch point $initial_branch_point is not valid"
+		    exit 1
+		fi
 	    fi
 	else
 	    echo "[ERROR] Could not find source repository $src. remote"
