scc/spp: indent if/else branch
Signed-off-by: Andreas Fenkart <afenkart@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/spp b/tools/spp
--- a/tools/spp
+++ b/tools/spp
@@ -107,8 +107,8 @@ if [ -z "$infiles" ]; then
 else
     for f in $infiles; do
 	if [ ! -f "$f" ]; then
-	err "ERROR. input file \"$f\" does not exist"
-	exit 1
+	    err "ERROR. input file \"$f\" does not exist"
+	    exit 1
 	fi
     done
 fi
