updateme: avoid double inclusion of .scc files
When a .cfg is passed via the command line, the tools check to see if
a .scc file already include that fragment, and then avoid generating
a feature for that fragment (since it already has an explicit .scc
structure).

The tools then ensure that the .scc file is put into the meta-series
processing pipeline .. so the configuration fragment will be applied.

Unfortunately, this forced inclusion of the .scc file in the pipeline
can lead to duplicate processing, since there are other includes and
structure of the files in play.

To avoid the duplicate processing, if a .cfg file is already included
by a fragment, we trust the structure of the includes and don't force
it to be processed.

[YOCTO: #8486]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/updateme b/tools/updateme
--- a/tools/updateme
+++ b/tools/updateme
@@ -246,14 +246,44 @@ migrate_cfg() {
 	# check to see if a .scc file already includes the fragment
 	gen_feature=
 	if [ -n "$scc_files" ]; then
-		matches=`grep -l $b $scc_files`
+		matches=`grep -l $b $scc_files | head -n1`
 		if [ -z "$matches" ]; then
 			gen_feature=t
 		else
 			feat_name="$matches"
 		fi
+
+		# secondary check.
+		#
+		# We just found that a .scc file already includes a fragment that
+		# cam in on the command line, so we plan to force it to be applied
+		# via the "extra features".
+		#
+		# BUT
+		#
+		# If another .scc file in the same directory, or on the command line
+		# has the file we found above already listed, we are forcing a double
+		# include, and that can be a bad thing.
+		#
+		grep -q `basename $matches` $scc_files
+		if [ $? -eq 0 ]; then
+		    # we have a match, and the file that contains this fragment is
+		    # already included. So we don't generate a feature, and we don't
+		    # force this feature
+		    if [ -n "$verbose" ]; then
+			echo "migrate cfg: config `basename $c` is already included, feature generation not required"
+		    fi
+		    return
+                fi
+
+                if [ -n "$verbose" ]; then
+                    echo "migrate cfg: using feature $feat_name for config `basename $c`"
+                fi
 	else
 		gen_feature=t
+		if [ -n "$verbose" ]; then
+		    echo "migrate cfg: no includes found for config `basename $c`, generating feature"
+		fi
 	fi
 
 	if [ -n "$gen_feature" ]; then
@@ -266,7 +296,7 @@ migrate_cfg() {
 
 		feat_name="$meta_dir/cfg/scratch/obj/$dirname/$gen_feature_name"
 	fi
-	
+
 	# we've generated the feature, make sure it can be found
 	add_search_include_dir $meta_dir/cfg/scratch/obj/$dirname
 
@@ -507,6 +537,13 @@ do_update() {
 
 	# this builds and applies the meta-series
 	( cd $meta_dir/cfg/scratch/obj
+
+	    if [ -n "$verbose" ]; then
+		echo "generating meta series"
+		echo "	 features: $extra_features"
+		echo "	 addons: $addon_features"
+	    fi
+
 	    scc --force -o ../$ktgt-meta $includes $top_tgt $extra_features $addon_features
 	    if [ $? -ne 0 ]; then
 		echo "ERROR. A meta series could not be created for $top_tgt"
